/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pbetkier' at '6/21/14 5:53 PM' with Gradle 1.11
 *
 * @author pbetkier, @date 6/21/14 5:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
